package:
  name: nglview
  version: "0.4"

source:
  fn: nglview-0.4.tar.gz
  url: https://github.com/arose/nglview/archive/v0.4.tar.gz

build:
  number: 0 

requirements:
  build:
    - python
    - setuptools
    - jupyter

  run:
    - python
    - jupyter
    - ipywidgets

test:
  # Python imports
  imports:
    - nglview
    - nglview.datafiles
    - nglview.html

about:
  home: https://github.com/arose/nglview
  license: MIT License
  summary: 'IPython widget to interactively view molecular structures and trajectories.'

